### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by ghost** [benjaminleroy/ggDiagnose#1]
Hi, I would like some help in figuring out why I am unable to install the package. Thanks.

devtools::install_github("benjaminleroy/ggDiagnose")
Downloading GitHub repo benjaminleroy/ggDiagnose@master
√  checking for file 'C:\Users\Admin\AppData\Local\Temp\RtmpA5uuHQ\remotesc068750548b3\benjaminleroy-ggDiagnose-e285257/DESCRIPTION' (1.1s)
-  preparing 'ggDiagnose': (710ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (417ms)
-  checking for empty or unneeded directories
-  building 'ggDiagnose_0.1.0.tar.gz'
   
Installing package into ‘D:/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'ggDiagnose' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
ARGUMENT 'Admin\AppData\Local\Temp\RtmpwT6et1\Rin126d41506f1f' __ignored__

Error: unexpected symbol in "set HOME_DIR"
Execution halted
ERROR: lazy loading failed for package 'ggDiagnose'
* removing 'D:/Documents/R/win-library/3.6/ggDiagnose'
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/Admin/AppData/Local/Temp/RtmpA5uuHQ/filec0687f296ec0/ggDiagnose_0.1.0.tar.gz’ had non-zero exit status

**Comment by benjaminleroy** [comment]
Hi @jdagz28 - this seems to be a problem with your windows environment. Maybe set the location for the library. See comment here:
```r
Installing package into ‘D:/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
```

Also, my recommendation is actually to use [`ggfortify`](https://github.com/sinhrks/ggfortify). It's more expansive - and I didn't realize that it was already created. *Feel free to use this package, I just don't plan to work too much on it - may try to contribute to ggfortify some day.*

**Comment by benjaminleroy** [comment]
please feel free to submit another issue if this isn't helpful

**Comment by ghost** [comment]
> 
> 
> please feel free to submit another issue if this isn't helpful

Hi, I have already fixed the issue. It turned out that there was a problem in installing the package if the username has spaces (which i changed to Admin in my post). 

Thanks a lot.
